using SharedKernel;

namespace Orders.Domain.Items;

/// <summary>
/// External insurance-policy reference data for one sold <see cref="Item"/> — 1:1, mutable, entered by an
/// operator (admin or producer) AFTER the sale, never generated by this platform (ADR-1/REQ-6.3). Kept as
/// its own aggregate rather than fields on <see cref="Item"/> because <c>Item</c> is INSERT-only (a
/// purchase-time snapshot written once through <see cref="Order"/>), while this data is mutable, written
/// by a different actor than the sale, and carries its own audit trail (<see cref="ItemPolicyAudit"/>) and
/// permission set — folding it into <c>Item</c> would force an UPDATE grant and a mutator onto an
/// otherwise-immutable snapshot aggregate (design.md "Architecture Overview").
/// </summary>
public sealed class ItemPolicy : Entity<Guid>
{
    /// <summary>The <see cref="Item"/> this record belongs to — unique, 1:1.</summary>
    public Guid OrderItemId { get; private set; }

    /// <summary>Tenant key, set once at <see cref="Create"/> and never changed by <see cref="Apply"/>.</summary>
    public Guid MerchantId { get; private set; }

    /// <summary>Null = not yet entered (REQ-1.7/1.11) — no dedicated "unset" enum member.</summary>
    public InsuranceCategory? InsuranceCategory { get; private set; }

    public ReferenceNumberType? ReferenceNumberType { get; private set; }

    public string? ReferenceNumber { get; private set; }

    /// <summary>สลักหลัง — requires a base <see cref="ReferenceNumber"/> already set (REQ-3.11).</summary>
    public string? EndorsementNumber { get; private set; }

    /// <summary>เลขใบเตือนต่ออายุ — requires a base <see cref="ReferenceNumber"/> already set (REQ-3.11).</summary>
    public string? RenewalReminderNumber { get; private set; }

    /// <summary>Generic reference to the insured object (e.g. ทะเบียนรถ) — not Motor-specific (REQ-1.8).</summary>
    public string? InsuredObjectReference { get; private set; }

    // Money stored as Amount+Currency scalar pairs (CODING_STANDARDS Money rule) rather than
    // ComplexProperty<Money?> — sidesteps the EF Core 10 optional-complex-type bug (efcore#38043/#37249),
    // per design.md Technology Decision #7. Both null = unset; both set = a paired premium (REQ-3.12).
    public decimal? NetPremiumAmount { get; private set; }
    public string? NetPremiumCurrency { get; private set; }
    public decimal? GrossPremiumAmount { get; private set; }
    public string? GrossPremiumCurrency { get; private set; }

    public PremiumRemittanceStatus PremiumRemittanceStatus { get; private set; } = PremiumRemittanceStatus.NotApplicable;

    /// <summary>Client-supplied local date the insurer's system deducted the premium (REQ-2.2) — never a
    /// server timestamp. Only meaningful while <see cref="PremiumRemittanceStatus"/> is
    /// <see cref="Orders.Domain.Items.PremiumRemittanceStatus.Deducted"/>; cleared otherwise (REQ-2.6).</summary>
    public DateOnly? DeductedAt { get; private set; }

    public DateTime CreatedAt { get; private set; }

    public DateTime UpdatedAt { get; private set; }

    public Money? NetPremium =>
        NetPremiumAmount is { } netAmount && NetPremiumCurrency is { } netCurrency
            ? Money.Of(netAmount, netCurrency)
            : null;

    public Money? GrossPremium =>
        GrossPremiumAmount is { } grossAmount && GrossPremiumCurrency is { } grossCurrency
            ? Money.Of(grossAmount, grossCurrency)
            : null;

    /// <summary>Parameterless ctor for EF Core materialisation only.</summary>
    private ItemPolicy() { }

    private ItemPolicy(Guid id, Guid orderItemId, Guid merchantId, DateTime nowUtc) : base(id)
    {
        OrderItemId = orderItemId;
        MerchantId = merchantId;
        CreatedAt = nowUtc;
        UpdatedAt = nowUtc;
    }

    /// <summary>
    /// Starts an empty (all-unset) record for an item — every REQ-1.2–1.6 field is null until the first
    /// <see cref="Apply"/> (REQ-1.7). <c>public</c> rather than the <c>internal</c> design.md sketched: this
    /// repo has no <c>InternalsVisibleTo</c> anywhere (deliberately, per
    /// <c>MerchantUserOutboxDispatcher.cs</c>/<c>MerchantRuntimeDbContextFactory.cs</c>) and the identical
    /// domain-factory-called-from-an-Application-handler shape (<see cref="Order.Create"/>) is already
    /// <c>public</c> — matching that precedent avoids introducing the one InternalsVisibleTo pattern the
    /// codebase has explicitly rejected elsewhere.
    /// </summary>
    public static ItemPolicy Create(Guid id, Guid orderItemId, Guid merchantId, DateTime nowUtc)
    {
        if (id == Guid.Empty)
            throw new ArgumentException("Id is required.", nameof(id));
        if (orderItemId == Guid.Empty)
            throw new ArgumentException("OrderItemId is required.", nameof(orderItemId));
        if (merchantId == Guid.Empty)
            throw new ArgumentException("MerchantId is required.", nameof(merchantId));

        return new ItemPolicy(id, orderItemId, merchantId, nowUtc);
    }

    /// <summary>
    /// Replaces every external-reference field, enforcing every write-path invariant (REQ-3). Every
    /// rejection is an <see cref="ArgumentException"/> (=> 400 per <c>ProblemDetailsExceptionHandler</c> —
    /// never <c>BadHttpRequestException</c>, which maps to 500).
    /// </summary>
    public void Apply(ItemPolicyInput input, DateTime nowUtc)
    {
        ArgumentNullException.ThrowIfNull(input);

        // Ref strings: trim, collapse blank to null (blank counts as "unset" per REQ-3.9's own wording).
        var referenceNumber = Normalize(input.ReferenceNumber);
        var endorsementNumber = Normalize(input.EndorsementNumber);
        var renewalReminderNumber = Normalize(input.RenewalReminderNumber);
        var insuredObjectReference = Normalize(input.InsuredObjectReference);

        // (type, value) paired both directions — REQ-3.9 / REQ-3.10.
        if (input.ReferenceNumberType is not null && referenceNumber is null)
            throw new ArgumentException(
                "ReferenceNumber is required when ReferenceNumberType is set.",
                nameof(ItemPolicyInput.ReferenceNumberType));
        if (referenceNumber is not null && input.ReferenceNumberType is null)
            throw new ArgumentException(
                "ReferenceNumberType is required when ReferenceNumber is set.",
                nameof(ItemPolicyInput.ReferenceNumber));

        // Endorsement/renewal ride on an existing base reference — REQ-3.11.
        if ((endorsementNumber is not null || renewalReminderNumber is not null) && referenceNumber is null)
            throw new ArgumentException(
                "EndorsementNumber/RenewalReminderNumber require a ReferenceNumber to already be set.",
                nameof(ItemPolicyInput.ReferenceNumber));

        // Net/gross both-or-neither — REQ-3.12.
        if (input.NetPremium is null != input.GrossPremium is null)
            throw new ArgumentException(
                "NetPremium and GrossPremium must both be set or both be unset.",
                nameof(ItemPolicyInput.NetPremium));

        if (input.NetPremium is { } netPremium && input.GrossPremium is { } grossPremium)
        {
            // Currency fixed THB — REQ-3.8.
            if (!string.Equals(netPremium.Currency, "THB", StringComparison.Ordinal))
                throw new ArgumentException("NetPremium currency must be THB.", nameof(ItemPolicyInput.NetPremium));
            if (!string.Equals(grossPremium.Currency, "THB", StringComparison.Ordinal))
                throw new ArgumentException("GrossPremium currency must be THB.", nameof(ItemPolicyInput.GrossPremium));

            // Net <= Gross — REQ-3.7.
            if (netPremium.Amount > grossPremium.Amount)
                throw new ArgumentException(
                    "NetPremium must not exceed GrossPremium.", nameof(ItemPolicyInput.NetPremium));
        }

        // Deducted <=> DeductedAt present — REQ-2.3/2.4; not-future, basis = Thai local date — REQ-2.5.
        if (input.PremiumRemittanceStatus == PremiumRemittanceStatus.Deducted)
        {
            if (input.DeductedAt is null)
                throw new ArgumentException(
                    "DeductedAt is required when PremiumRemittanceStatus is Deducted.",
                    nameof(ItemPolicyInput.DeductedAt));

            var todayThai = DateOnly.FromDateTime(nowUtc.AddHours(7));
            if (input.DeductedAt.Value > todayThai)
                throw new ArgumentException(
                    "DeductedAt must not be in the future.", nameof(ItemPolicyInput.DeductedAt));
        }

        InsuranceCategory = input.InsuranceCategory;
        ReferenceNumberType = input.ReferenceNumberType;
        ReferenceNumber = referenceNumber;
        EndorsementNumber = endorsementNumber;
        RenewalReminderNumber = renewalReminderNumber;
        InsuredObjectReference = insuredObjectReference;
        NetPremiumAmount = input.NetPremium?.Amount;
        NetPremiumCurrency = input.NetPremium?.Currency;
        GrossPremiumAmount = input.GrossPremium?.Amount;
        GrossPremiumCurrency = input.GrossPremium?.Currency;
        PremiumRemittanceStatus = input.PremiumRemittanceStatus;
        // DeductedAt only ever means something while Deducted — this both satisfies REQ-2.4 (NotApplicable
        // never requires it) and REQ-2.6 (revert to NotApplicable clears it) with one rule.
        DeductedAt = input.PremiumRemittanceStatus == PremiumRemittanceStatus.Deducted ? input.DeductedAt : null;
        UpdatedAt = nowUtc;
    }

    private static string? Normalize(string? value)
    {
        if (value is null)
            return null;
        var trimmed = value.Trim();
        return trimmed.Length == 0 ? null : trimmed;
    }
}
