namespace Orders.Domain.Items;

/// <summary>What kind of value <see cref="ItemPolicy.ReferenceNumber"/> holds (REQ-1.3) — เลขกรมธรรม์
/// (<see cref="PolicyNumber"/>) or เลขรับแจ้ง (<see cref="NotificationNumber"/>), issued by the external
/// insurer, never generated by this platform (ADR-1/REQ-6.3).</summary>
public enum ReferenceNumberType
{
    PolicyNumber = 0,
    NotificationNumber = 1,
}
