<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Products\Products.Application\Products.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Products\Products.Domain\Products.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Products\Products.Infrastructure\Products.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

</Project>
