<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PlatformLayer>Domain</PlatformLayer>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Pol.UnitTests" />
    <InternalsVisibleTo Include="Pol.ArchitectureTests" />
    <InternalsVisibleTo Include="Pol.IntegrationTests" />
  </ItemGroup>

</Project>
