<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RunSettingsFilePath>$(MSBuildProjectDirectory)/Pol.IntegrationTests.runsettings</RunSettingsFilePath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Pol.Api/Pol.Api.csproj" Aliases="global,ApiHost" />
    <ProjectReference Include="../../src/Pol.Domain/Pol.Domain.csproj" />
    <ProjectReference Include="../../src/Pol.Application/Pol.Application.csproj" />
    <ProjectReference Include="../../src/Pol.Infrastructure/Pol.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
